import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { test } from 'node:test'

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const html = readFileSync(resolve(rootDir, 'SSM-Builder.html'), 'utf8')
const pkg = JSON.parse(readFileSync(resolve(rootDir, 'package.json'), 'utf8'))
const pagesWorkflow = readFileSync(resolve(rootDir, '.github/workflows/deploy-pages.yml'), 'utf8')
const manifest = readFileSync(resolve(rootDir, 'pwa/manifest.webmanifest'), 'utf8')
const serviceWorker = readFileSync(resolve(rootDir, 'pwa/sw.js'), 'utf8')

test('offline updater checks the SSM-Builder GitHub release once on boot', () => {
  assert.match(html, /<title>SSM Builder<\/title>/)
  assert.match(html, /<h1>SSM Builder<\/h1>/)
  assert.match(html, new RegExp(`const APP_VERSION = '${pkg.version.replaceAll('.', '\\.')}'`))
  assert.match(
    html,
    /const UPDATE_RELEASE_API = 'https:\/\/api\.github\.com\/repos\/noahfgarrett\/SSM-Builder\/releases\/latest'/,
  )
  assert.match(
    html,
    /const UPDATE_RAW_BASE = 'https:\/\/raw\.githubusercontent\.com\/noahfgarrett\/SSM-Builder'/,
  )
  assert.match(html, /function checkForAppUpdate\(/)
  assert.match(html, /function isPwaHostedApp\(\)/)
  assert.match(html, /meta\[name="ssm-builder-pwa"\]\[content="true"\]/)
  assert.match(html, /if\(!isPwaHostedApp\(\)\)checkForAppUpdate\(\)\.then\(info=>\{/)
  assert.doesNotMatch(html, /serviceWorker|manifest\.json|register\(/)
})

test('update selection requires a plain HTML asset and can prefer a compressed asset', () => {
  assert.match(html, /function selectUpdateAsset\(assets\)/)
  assert.match(html, /\.endsWith\('\.html'\)/)
  assert.match(html, /\.endsWith\('\.html\.gz'\)/)
  assert.match(html, /downloadKind:'gzip-html'/)
  assert.match(html, /fallbackAssetApiUrl:htmlAsset\.url/)
})

test('clicking update downloads the tagged raw HTML file as a local HTML file', () => {
  assert.match(html, /function downloadUpdateFile\(info\)/)
  assert.match(html, /function rawUpdateUrl\(tagName,assetName\)/)
  assert.match(html, /rawDownloadUrl:rawUpdateUrl\(tagName,rawName\)/)
  assert.match(html, /function fetchRawUpdateHtml\(rawUrl,version\)/)
  assert.match(html, /headers:\{Accept:'text\/html,text\/plain,\*\/\*'\}/)
  assert.match(html, /html\.includes\("const APP_VERSION = '"\+version\+"'"\)/)
  assert.match(html, /source:'raw'/)
  assert.match(html, /headers:\{Accept:'application\/octet-stream'\}/)
  assert.match(html, /function versionedUpdateFilename\(version\)/)
  assert.match(html, /return 'SSM-Builder-v'\+cleanVersion\+'\.html'/)
  assert.match(html, /const filename=versionedUpdateFilename\(info\.version\)/)
  assert.match(html, /saveUpdateHtml\(htmlBlob,filename\)/)
  assert.match(html, /function saveUpdateFromUrl\(url,filename\)/)
  assert.match(html, /id="updateModal"/)
  assert.match(html, /id="updateDownload"/)
  assert.doesNotMatch(html, /window\.open\([^)]*github/i)
  assert.doesNotMatch(html, /Please try again from a fresh connection/)
})

test('standalone update downloads save directly without a share sheet fallback', () => {
  assert.match(html, /@media \(max-width:820px\)/)
  assert.match(html, /@media \(pointer:coarse\)/)
  assert.match(html, /function saveUpdateHtml\(htmlBlob,filename\)/)
  assert.match(html, /saveBlob\(htmlBlob,filename,'text\/html'\)/)
  assert.doesNotMatch(html, /navigator\.canShare/)
  assert.doesNotMatch(html, /navigator\.share/)
  assert.doesNotMatch(html, /shouldUseShareSheetForUpdate/)
  assert.doesNotMatch(html, /isIOSUpdateDevice/)
})

test('loader progress keeps a composited spinner and growing percent ring on iPad', () => {
  assert.match(html, /<div class="ring-spin">\s*<svg viewBox="0 0 96 96" aria-hidden="true">/)
  assert.match(html, /\.ring-spin\{[^}]*animation:ringspin 2\.4s linear infinite/)
  assert.match(html, /\.ring-prog\{[^}]*transition:stroke-dashoffset \.3s cubic-bezier\(\.22,1,\.36,1\)/)
  assert.match(html, /#overlay\.show \.ring-spin\{animation:ringspin 2\.4s linear infinite!important\}/)
  assert.match(html, /#overlay\.show \.ring-prog\{transition:stroke-dashoffset \.3s cubic-bezier\(\.22,1,\.36,1\)!important\}/)
})

test('changelog modal is available from update tabs and the version link', () => {
  assert.match(html, /const CHANGELOG=\[/)
  assert.match(html, /version:'1\.1\.2'/)
  assert.match(html, /version:'1\.1\.1'/)
  assert.match(html, /version:'1\.1\.0'/)
  assert.match(html, /version:'1\.0\.9'/)
  assert.match(html, /version:'1\.0\.8'/)
  assert.match(html, /version:'1\.0\.7'/)
  assert.match(html, /version:'1\.0\.6'/)
  assert.match(html, /version:'1\.0\.5'/)
  assert.match(html, /version:'1\.0\.4'/)
  assert.match(html, /version:'1\.0\.3'/)
  assert.match(html, /version:'1\.0\.2'/)
  assert.match(html, /type:'feature'/)
  assert.match(html, /type:'fix'/)
  assert.match(html, /type:'major'/)
  assert.match(html, /Improved large-dataset tab performance with virtualized Review and Comparison tables/)
  assert.match(html, /Improved Comparison tab performance for large working-copy reviews/)
  assert.match(html, /Added session caching so Hierarchy, Review, and Comparison tabs reopen instantly/)
  assert.match(html, /Fixed changelog entries crowding together instead of scrolling/)
  assert.match(html, /class="update-tab" id="changelogTab"/)
  assert.match(html, /id="changelogPanel"/)
  assert.match(html, /function renderChangelog\(info\)/)
  assert.match(html, /function showAppChangelog\(\)/)
  assert.match(html, /id="versionLink"/)
  assert.match(html, /\$\('#versionLink'\)\.onclick=showAppChangelog/)
  assert.match(html, /\.change-entry\.major/)
  assert.match(html, /\.change-entry\.feature/)
  assert.match(html, /\.change-entry\.fix/)
  assert.match(html, /\.update-card\.wide\{[^}]*height:min\(500px,calc\(100vh - 40px\)\)/)
  assert.match(html, /#updatePanel:not\(\[hidden\]\),#changelogPanel:not\(\[hidden\]\)\{display:flex;flex:1;min-height:0;flex-direction:column\}/)
  assert.match(html, /\.changelog-intro\{[^}]*flex:0 0 auto/)
  assert.match(html, /\.changelog-list\{[^}]*flex:1;min-height:0;max-height:none;overflow-y:auto;overflow-x:hidden/)
  assert.match(html, /\.change-entry\{[^}]*flex:0 0 auto/)
})

test('result tabs use session-only in-memory panel caches', () => {
  assert.match(html, /viewCache:\{tree:null,review:new Map\(\),reviewRows:new Map\(\),compare:new Map\(\),compareRows:new Map\(\)\}/)
  assert.match(html, /const RESULT_PANEL_CACHE_LIMIT=24/)
  assert.match(html, /function clearResultCache\(\)/)
  assert.match(html, /function rememberPanelCache\(name,key,el,scrollSel\)/)
  assert.match(html, /function restorePanelCache\(name,key,el,scrollSel\)/)
  assert.match(html, /function rememberTreePanel\(\)/)
  assert.match(html, /function restoreTreePanel\(\)/)
  assert.match(html, /function reviewPanelCacheKey\(\)/)
  assert.match(html, /function comparePanelCacheKey\(\)/)
  assert.match(html, /if\(isPanelCacheLive\(el,key\)\)\{wireReviewPanel\(\);renderReviewRowsVirtual\(getReviewRowsCache\(\),key,el\);return;\}/)
  assert.match(html, /if\(restorePanelCache\('review',key,el,'#revCard'\)\)\{wireReviewPanel\(\);renderReviewRowsVirtual\(getReviewRowsCache\(\),key,el\);return;\}/)
  assert.match(html, /if\(isPanelCacheLive\(el,key\)\)\{wireComparePanel\(\);renderCompareRowsVirtual\(getCompareRowsCache\(S\.cmpFilter,S\.cmpSearch\),key,el\);scheduleComparePrewarm\(S\.cmpFilter,S\.cmpSearch\);return;\}/)
  assert.match(html, /if\(restorePanelCache\('compare',key,el,'#cmpCard'\)\)\{wireComparePanel\(\);renderCompareRowsVirtual\(getCompareRowsCache\(S\.cmpFilter,S\.cmpSearch\),key,el\);scheduleComparePrewarm\(S\.cmpFilter,S\.cmpSearch\);return;\}/)
  assert.match(html, /clearResultCache\(\);/)
  assert.doesNotMatch(html, /localStorage|sessionStorage|indexedDB/)
})

test('large review and comparison tables virtualize rows and cache search work', () => {
  assert.match(html, /const VIRTUAL_ROW_HEIGHT=44/)
  assert.match(html, /const VIRTUAL_OVERSCAN=16/)
  assert.match(html, /const VIRTUAL_MAX_DOM_ROWS=180/)
  assert.match(html, /function virtualSpacerRow\(height,colspan\)/)
  assert.match(html, /function virtualRowsHtml\(rows,makeRow,start,end,cache\)/)
  assert.match(html, /function mountVirtualRows\(tbodySel,rows,makeRow,emptyHtml,opts\)/)
  assert.match(html, /tb\.dataset\.virtualStart/)
  assert.match(html, /tb\.dataset\.virtualRows/)
  assert.match(html, /Math\.floor\(card\.scrollTop\/VIRTUAL_ROW_HEIGHT\)-VIRTUAL_OVERSCAN/)
  assert.match(html, /Math\.min\(Math\.max\(0,rows\.length-visible\),Math\.max\(0,Math\.floor\(card\.scrollTop\/VIRTUAL_ROW_HEIGHT\)-VIRTUAL_OVERSCAN\)\)/)
  assert.match(html, /requestAnimationFrame\(\(\)=>\{if\(token===_virtualTok\)render\(\);\}\)/)
  assert.match(html, /function idleFrame\(\)/)
  assert.match(html, /requestIdleCallback/)
  assert.match(html, /function reviewSearchKey\(r\)/)
  assert.match(html, /function reviewRowsCacheKey\(\)/)
  assert.match(html, /function getReviewRowsCache\(\)/)
  assert.match(html, /function renderReviewRowsVirtual\(rec,key,el\)/)
  assert.match(html, /searchKey:reviewSearchKey\(rec\)/)
  assert.match(html, /r\.searchKey\.includes\(q\)/)
  assert.match(html, /const CMP_FILTERS=\['all','off','nohit','match'\]/)
  assert.match(html, /compareBuckets:\{all:\[\],off:\[\],nohit:\[\],match:\[\]\}/)
  assert.match(html, /function compareSearchKey\(r\)/)
  assert.match(html, /function comparePanelCacheKeyFor\(filter,search\)/)
  assert.match(html, /function compareRowsCacheKey\(filter,search\)/)
  assert.match(html, /function getCompareRowsCache\(filter,search\)/)
  assert.match(html, /function renderCompareRowsVirtual\(rec,key,el\)/)
  assert.match(html, /function prewarmCompareRows\(filter,search,token\)/)
  assert.match(html, /function scheduleComparePrewarm\(activeFilter,search\)/)
  assert.match(html, /S\.compareBuckets=\{all:S\.compare,off:S\.compare\.filter\(r=>r\.status==='off'\),nohit:S\.compare\.filter\(r=>r\.status==='nohit'\),match:S\.compare\.filter\(r=>r\.status==='match'\)\}/)
  assert.match(html, /searchKey:compareSearchKey\(rec\)/)
  assert.match(html, /const base=\(S\.compareBuckets&&S\.compareBuckets\[filter\]\)\|\|S\.compare/)
  assert.match(html, /const order=\[activeFilter,\.\.\.CMP_FILTERS\.filter\(f=>f!==activeFilter\)\]/)
  assert.match(html, /await prewarmCompareRows\(filter,search,token\)/)
  assert.match(html, /renderCompareRowsVirtual\(getCompareRowsCache\(S\.cmpFilter,S\.cmpSearch\),key,el\)/)
  assert.match(html, /scheduleComparePrewarm\(S\.cmpFilter,S\.cmpSearch\)/)
  assert.match(html, /card\.addEventListener\('scroll',onScroll,\{passive:true\}\)/)
  assert.match(html, /rememberPanelCache\('compare',key,el,'#cmpCard'\)/)
})

test('review tab groups columns by their source system', () => {
  assert.match(html, /<table class="dtable review">/)
  assert.match(html, /<th colspan="3" class="source-head cable">/)
  assert.match(html, /<th colspan="3" class="source-head cable"><span>Cable Schedule<\/span><\/th>/)
  assert.match(html, /<th colspan="2" class="source-head ep">/)
  assert.match(html, /<th colspan="2" class="source-head ep"><span>Easy Power<\/span><\/th>/)
  assert.match(html, /\.dtable\.review thead th\.sub\{[^}]*top:44px/)
  assert.match(html, /\.source-head\{[^}]*text-align:center!important/)
  assert.match(html, /\.dtable\.review \.source-head\.ep,\s*\.dtable\.review thead tr:nth-child\(2\) th:nth-child\(4\),\s*\.dtable\.review tbody td:nth-child\(4\)\{box-shadow:inset 1px 0 0 rgba\(148,163,184,\.35\)\}/)
  assert.match(html, /\.source-head span\{[^}]*font-size:11px/)
  assert.match(html, /\.source-head span::before/)
  assert.match(html, /\.source-head span::after/)
  assert.doesNotMatch(html, /source-kicker/)
  assert.doesNotMatch(html, /source-title/)
  assert.doesNotMatch(html, /To \/ From/)
  assert.doesNotMatch(html, /Source \/ Downstream \/ ID Name/)
})

test('comparison and SSM exports replace duplicated dependency values with N/A', () => {
  assert.match(html, /function sameRegisterValue\(a,b\)\{return clean\(a\)\.toLowerCase\(\)===clean\(b\)\.toLowerCase\(\);\}/)
  assert.match(html, /function registerDepValue\(parent,dep\)\{/)
  assert.match(html, /return d&&sameRegisterValue\(parent,d\)\?'N\/A':d;/)
  assert.match(html, /function ssmRegisterResolve\(r\)\{const o=ssmResolve\(r\);return \{\.\.\.o,dep:registerDepValue\(o\.parent,o\.dep\)\};\}/)
  assert.match(html, /const curParent=a\?a\.parent:''/)
  assert.match(html, /const curDep=a\?registerDepValue\(a\.parent,a\.dep\):''/)
  assert.match(html, /const wcParent=b\?b\.parent:''/)
  assert.match(html, /const wcDep=b\?registerDepValue\(b\.parent,b\.dep\):''/)
  assert.match(html, /status=\(eq\(curParent,wcParent\)&&eq\(curDep,wcDep\)\)\?'match':'off'/)
  assert.equal((html.match(/const \{equip,parent,dep\}=ssmRegisterResolve\(r\)/g) || []).length, 2)
})

test('LotusWorks logo is embedded in the single HTML header', () => {
  assert.match(html, /<img class="lotus-logo" alt="LotusWorks" src="data:image\/png;base64,/)
  assert.match(html, /\.lotus-logo\{order:0;height:66px/)
  assert.match(html, /--brand-main-left:max\(var\(--content-left\),var\(--brand-safe-left\)\)/)
  assert.match(html, /\.brand \.mark\{position:absolute;left:var\(--brand-main-local\)/)
  assert.match(html, /\.lotus-logo\{position:absolute;left:calc\(22px - \(\(100vw - 1080px\)\/2\)\)/)
  assert.match(html, /\.lotus-logo\{height:60px;max-width:195px/)
  assert.doesNotMatch(html, /LotusWorks_Logo_TP\.png/)
  assert.doesNotMatch(html, /__LOTUS_LOGO_DATA_URI__/)
})

test('GitHub Pages PWA publishing follows main app updates', () => {
  assert.match(pagesWorkflow, /on:\n  workflow_dispatch:/)
  assert.match(pagesWorkflow, /\n  push:\n    branches: \[main\]\n    paths:/)
  assert.match(pagesWorkflow, /- SSM-Builder\.html/)
  assert.match(pagesWorkflow, /- pwa\/\*\*/)
  assert.match(pagesWorkflow, /- \.github\/workflows\/deploy-pages\.yml/)
  assert.doesNotMatch(pagesWorkflow, /^\s+release:/m)
  assert.doesNotMatch(pagesWorkflow, /^\s+schedule:/m)
  assert.match(pagesWorkflow, /uses: actions\/configure-pages@v5/)
  assert.match(pagesWorkflow, /uses: actions\/upload-pages-artifact@v4/)
  assert.match(pagesWorkflow, /uses: actions\/deploy-pages@v4/)
  assert.match(pagesWorkflow, /cp SSM-Builder\.html dist\/index\.html/)
  assert.match(pagesWorkflow, /meta name="ssm-builder-pwa" content="true"/)
  assert.match(pagesWorkflow, /replace\("<\/head>", pwa_head \+ "<\/head>", 1\)/)
  assert.match(pagesWorkflow, /rpartition\("<\/body>"\)/)
  assert.match(manifest, /"display": "standalone"/)
  assert.match(manifest, /"start_url": "\.\/"/)
  assert.match(serviceWorker, /const CACHE_NAME = 'ssm-builder-pwa-v1'/)
  assert.match(serviceWorker, /fetch\(request\)/)
  assert.match(serviceWorker, /caches\.match\('\.\/index\.html'\)/)
})
